"$schema" = "https://starship.rs/config-schema.json"


add_newline = true

# format = "$all"

format = """
$localip\
$shlvl\
$shell\
$env_var\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$sudo\
$fill\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$jobs\
$status\
$os\
$container\
$battery\
$cmd_duration\
$time\
$line_break\
$hostname\
$username\
$character\
"""

[aws]
format = '[$symbol($profile)(\($region\))(\[$duration )]($style)\]'
disabled = true

[bun]
format = '[$symbol($version)]($style) '

[c]
format = '[$symbol($version(-$name))]($style) '

[cmake]
format = '[$symbol($version)]($style) '

[cmd_duration]
format = '[⏱ $duration]($style) '

[cobol]
format = '[$symbol($version)]($style) '

[conda]
format = '[$symbol$environment]($style) '

[crystal]
format = '[$symbol($version)]($style) '

[daml]
format = '[$symbol($version)]($style) '

[dart]
format = '[$symbol($version)]($style) '
[deno]
format = '[$symbol($version)]($style) '

[docker_context]
format = '[$symbol$context]($style) '

[dotnet]
format = '[$symbol($version)(🎯 $tfm)]($style) '

[elixir]
format = '[$symbol($version \(OTP $otp_version\))]($style) '

[elm]
format = '[$symbol($version)]($style) '

[erlang]
format = '[$symbol($version)]($style) '

[fennel]
format = '[$symbol($version)]($style) '

[fossil_branch]
format = '[$symbol$branch]($style) '

[gcloud]
format = '[$symbol$account(@$domain)(\($region\))]($style) '

[git_branch]
format = '[$symbol$branch]($style) '

[git_status]
format = '([ $all_status$ahead_behind ]($style)) '
style = "bold yellow"

[golang]
format = '[$symbol($version)]($style) '

[gradle]
format = '[$symbol($version)]($style) '

[guix_shell]
format = '[$symbol]($style) '

[haskell]
format = '[$symbol($version)]($style) '

[haxe]
format = '[$symbol($version)]($style) '

[helm]
format = '[$symbol($version)]($style) '

[hg_branch]
format = '[$symbol$branch]($style) '

[java]
format = '[$symbol($version)]($style) '

[julia]
format = '[$symbol($version)]($style) '

[kotlin]
format = '[$symbol($version)]($style) '

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style) '

[lua]
format = '[$symbol($version)]($style) '

[memory_usage]
format = '$symbol[$ram( | $swap)]($style) '

[meson]
format = '[$symbol$project]($style) '

[nim]
format = '[$symbol($version)]($style) '

[nix_shell]
format = '[$state]($style) '

[nodejs]
format = '[$symbol($version)]($style) '

[ocaml]
format = '[$symbol($version)(\($switch_indicator$switch_name\))]($style) '

[opa]
format = '[$symbol($version)]($style) '

[openstack]
format = '[$symbol$cloud(\($project\))]($style) '

[os]
format = '[$symbol]($style) '

[package]
format = '[$symbol$version]($style) '
disabled = true

[perl]
format = '[$symbol($version)]($style) '

[php]
format = '[$symbol($version)]($style) '

[pijul_channel]
format = '[$symbol$channel]($style) '

[pulumi]
format = '[$symbol$stack]($style) '

[purescript]
format = '[$symbol($version)]($style) '

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '

[raku]
format = '[$symbol($version-$vm_version)]($style) '

[red]
format = '[$symbol($version)]($style) '

[ruby]
format = '[$symbol($version)]($style) '

[rust]
format = '[$symbol($version)]($style) '

[scala]
format = '[$symbol($version)]($style) '

[spack]
format = '[$symbol$environment]($style) '

[sudo]
format = '[as $symbol]($style) '

[swift]
format = '[$symbol($version)]($style) '

[terraform]
format = '[$symbol$workspace]($style) '

[time]
format = '[$time]($style) '
disabled = false
use_12hr = false

[username]
format = '[$user]($style) '

[vagrant]
format = '[$symbol($version)]($style) '

[vlang]
format = '[$symbol($version)]($style) '

[zig]
format = '[$symbol($version)]($style) '

[solidity]
format = '[$symbol($version)]($style) '

[git_metrics]
disabled = false

[direnv]
disabled = true

[directory]
truncate_to_repo = false
truncation_length = 10
style = "bold blue"

[fill]
symbol = " "

[hostname]
format = '[$hostname]($style) '
style = "bold #999999"
