-- load visually obvious plugins first
require("plugins.theme")
require("plugins.tint")
require("plugins.lualine")

-- everything else
require("plugins.autopairs")
require("plugins.autosave")
require("plugins.blink")
require("plugins.conform")
require("plugins.copilot")
require("plugins.dap")
require("plugins.diffview")
require("plugins.fzf")
require("plugins.gitsigns")
require("plugins.grug-far")
require("plugins.harpoon")
require("plugins.indent-blankline")
require("plugins.lsp")
require("plugins.nvim-various-textobjs")
require("plugins.nvim-web-devicons")
require("plugins.oil")
require("plugins.tmux")
require("plugins.treesitter")
require("plugins.undotree")
require("plugins.vim-fugitive")
require("plugins.which-key")
require("plugins.zk")
