vim.g.mapleader = " "
vim.g.maplocalleader = " "

vim.o.hlsearch = false
vim.o.number = true
vim.o.relativenumber = true
vim.o.hidden = true
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.shiftwidth = 4
vim.o.expandtab = true
vim.o.smartindent = true
vim.o.scrolloff = 12
vim.o.updatetime = 100
vim.o.colorcolumn = "120"
vim.o.breakindent = true
vim.o.undofile = true
vim.o.swapfile = false
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.wo.signcolumn = "yes"
vim.o.termguicolors = true
vim.o.completeopt = "menuone,noselect"
