name: Build Flake

on:
  push:
    branches:
      - main
    paths:
      - '**'
  pull_request:
    branches:
      - main
    paths:
      - '**'

jobs:
  build-starter-template:
    uses: ./.github/workflows/build-template.yaml
    with:
      template: 'vinnix'
      arch: 'x86_64-linux'
