name: Build Flake

on:
  push:
    branches:
      - master
    paths:
      - '**'
  pull_request:
    branches:
      - master
    paths:
      - '**'

jobs:
  build-starter-template:
    uses: ./.github/workflows/build-template.yaml
    with:
      derivation: 'nixosConfigurations.vinnix.config.system.build.toplevel'
